# Generated by Django 6.0.3 on 2026-03-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_add_other_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='banquetbooking',
            name='banquet_type',
            field=models.CharField(choices=[('birthday', 'Birthday Celebration'), ('wedding', 'Wedding Ceremony'), ('engagement', 'Engagement Party'), ('anniversary', 'Anniversary Celebration'), ('ceremony', 'Naming Ceremony'), ('general', 'General Banquet Event'), ('other', 'Other Banquet')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='banquetbooking',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
