# Generated by Django 5.2.1 on 2026-03-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Add Photos'},
        ),
    ]
