# Generated by Django 5.2.1 on 2026-03-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_roombooking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
