# Generated by Django 6.0.3 on 2026-03-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_delete_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetbooking',
            name='banquet_type',
            field=models.CharField(choices=[('birthday', 'Birthday Celebration'), ('wedding', 'Wedding Ceremony'), ('engagement', 'Engagement Party'), ('anniversary', 'Anniversary Celebration'), ('ceremony', 'Naming Ceremony'), ('baby-shower', 'Baby Shower'), ('general', 'General Banquet Event')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='room_type',
            field=models.CharField(choices=[('classic', 'Classic Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite Room')], default='classic', max_length=20),
        ),
    ]
