# Generated by Django 6.0.3 on 2026-03-10 11:45

from django.db import migrations, connection


def fix_decimal_data(apps, schema_editor):
    """
    Fix corrupted decimal data in BanquetBooking table
    """
    # Use raw SQL to avoid Django's decimal conversion issues
    with connection.cursor() as cursor:
        try:
            # Update price_per_person to valid decimal values
            cursor.execute("""
                UPDATE bookings_banquetbooking 
                SET price_per_person = 0.00 
                WHERE price_per_person IS NULL OR 
                      CAST(price_per_person AS TEXT) NOT GLOB '*[0-9]*'
            """)
            
            # Update total_price to valid decimal values  
            cursor.execute("""
                UPDATE bookings_banquetbooking 
                SET total_price = 0.00 
                WHERE total_price IS NULL OR 
                      CAST(total_price AS TEXT) NOT GLOB '*[0-9]*'
            """)
            
            # Set reasonable default values
            cursor.execute("""
                UPDATE bookings_banquetbooking 
                SET price_per_person = CASE 
                    WHEN price_per_person = 0.00 THEN 2499.00
                    ELSE price_per_person 
                END,
                total_price = CASE 
                    WHEN total_price = 0.00 THEN price_per_person * guests
                    ELSE total_price 
                END
                WHERE price_per_person = 0.00 OR total_price = 0.00
            """)
            
        except Exception as e:
            print(f"Error fixing decimal data: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_banquetbooking_total_price_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_decimal_data, migrations.RunPython.noop),
    ]
